example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist, show_xml, show_json, show_json_by_id, register, login_user, logout_user, show_wishlist_ajax, create_wishlist

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_xml, name='show_xml'), #sesuaikan dengan nama fungsi yang dibuat
    path('json/', show_json, name='show_json'), #sesuaikan dengan nama fungsi yang dibuat
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'), #sesuaikan dengan nama fungsi yang dibuat
    path('register/', register, name='register'), #sesuaikan dengan nama fungsi yang dibuat
    path('login/', login_user, name='login'), #sesuaikan dengan nama fungsi yang dibuat
    path('logout/', logout_user, name='logout'), #sesuaikan dengan nama fungsi yang dibuat
    path('ajax/', show_wishlist_ajax, name='show_wishlist_ajax'),
    path("ajax/submit", create_wishlist, name="create_wishlist"),
]

wishlist/models.py
from django.db import models

# Create your models here.
class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from django.shortcuts import render
from wishlist.models import BarangWishlist
from django.http import HttpRequest, HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse

@login_required(login_url='/wishlist/login/')
# Create your views here.
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
    'list_barang': data_barang_wishlist,
    'nama': 'Hikam Fajduani',
    'last_login': request.COOKIES['last_login'],
}
    return render(request, "wishlist.html", context)

@login_required(login_url='/wishlist/login/')
# Create your views here.
def show_wishlist_ajax(request):
    context = {
    'nama': 'Hikam Fajduani',
    'last_login': request.COOKIES['last_login'],
}
    return render(request, "wishlist_ajax.html", context)

def show_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id (request,id):
    data = BarangWishlist.objects.filter(pk=id)
    # Jika JSON
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

def create_wishlist(request: HttpRequest):
    if request.method == "POST":
        nama_barang = request.POST.get("nama_barang")
        harga_barang = request.POST.get("harga_barang")
        deskripsi = request.POST.get("deskripsi")

        new_barang = BarangWishlist(
            nama_barang=nama_barang,
            harga_barang=harga_barang,
            deskripsi=deskripsi,
        )
        new_barang.save()
        return HttpResponse(
            serializers.serialize("json", [new_barang]),
            content_type="application/json",
        )

    return HttpResponse("Invalid method", status_code=405)

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}
{% block meta %}
<title>Login</title>
{% endblock meta %}
{% block content %}

<style>
    .text{
        font-size: 40px;
        font-family: sans-serif;
        font-weight: bold;
        text-align: center;
        color: #2466ea;
    }
    .text1{
        font-size: 15px;
        font-family: sans-serif;
        font-weight:300;
        text-align: center;
        color: #2466ea;
    }
    .position{
        top:11%;
        left:40%;
        width:100px;
        height:40px;
        position:sticky;
    }
</style>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>

<body>
<div class = "login">

    <h1 class="text">Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table class="position">
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul class="text1">
            {% for message in messages %}
                <li class="text1">{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'wishlist:register' %}" class="text1">Buat Akun</a>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</div>
</body>
{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>
<body>
<style>
    .text{
        font-size: 40px;
        font-family: sans-serif;
        font-weight: bold;
        text-align: center;
        color: #2466ea;
    }
    .position{
        top:11%;
        left:40%;
        width:100px;
        height:40px;
        position:fixed;
    }
    .daftar{
       top:11%;
       left:47%;
       width:100px;
       height:40px;
       position:sticky;
       z-index: 2;
       background:hsl(59, 100%, 77%); 
    }
</style>

<div class = "login">
    
    <h1 class="text">Formulir Registrasi</h1>  

        <form method="POST" class="position">  
            {% csrf_token %}  
            <table class="daftar">  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</div>  
</body>
{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}
{% block content %}

<style>
    .tabel{
      margin: 0 auto;
      text-align: center;
    }
    .text{
      font-size: 20px;
      font-family: sans-serif;
      font-weight: bold;
      text-align: center;
      color: #2466ea;
    }
    .text1{
      font-size: 20px;
      font-family: sans-serif;
      font-weight: bolder;
      text-align: center;
    }
    .tabelcolor{
      font-weight: bold;
      color: #ffffff;
      background-color: #2466ea;
    }
    .content-table{
      border-collapse: collapse;
      margin: auto;
      font-family: sans-serif;
      font-size: 0.9em;
      min-width: 400px;
      border-radius: 5px 5px 0 0;
      overflow: hidden;
      box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
      }
    .content-table th,
    .content-table td{
      padding: 12px 15px;
    }
    .content-table tbody tr{
      border-bottom: 1px solid #2466ea;
    }
    .content-table tbody tr:last-of-type{
      border-bottom: 2px solid #2466ea;
    }
    .button {
        padding: 2px 30px;
        border: none;
        background-color: #2466ea;
        font-family: sans-serif;
        font-weight: bold;
        font-size: 16px;
        color: #fff;
        border-radius: 50px;
        cursor: pointer;
        margin: auto;
        text-align: center;
    }
    button{
      margin: auto;
    }
</style>

<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Haii!!, {{nama}}</a>
    <button type="button"><a href="{% url 'wishlist:logout' %}" class="button">Logout</a></button>
    </div>
    </nav>

<h5 class="text">Nama:</h5>
<p class="text1">{{nama}}</p>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>
<body>
<table class="content-table">
    <tr class="tabelcolor">
    <th>Nama Barang</th>
    <th>Harga Barang</th>
    <th>Deskripsi</th>
    </tr>
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %} 
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
    {% for barang in list_barang %}
        <tr>
            <th>{{barang.nama_barang}}</th>
            <th>{{barang.harga_barang}}</th>
            <th>{{barang.deskripsi}}</th>
        </tr>
    {% endfor %}
</table>
<h5 class="text1">Sesi terakhir login: {{ last_login }}</h5>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>
{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}
{% block content %}

<style>
    .tabel{
      margin: 0 auto;
      text-align: center;
    }
    .text{
      font-size: 20px;
      font-family: sans-serif;
      font-weight: bold;
      text-align: center;
      color: #2466ea;
    }
    .text1{
      font-size: 20px;
      font-family: sans-serif;
      font-weight: bolder;
      text-align: center;
    }
    .tabelcolor{
      font-weight: bold;
      color: #ffffff;
      background-color: #2466ea;
    }
    .content-table{
      border-collapse: collapse;
      margin: auto;
      font-family: sans-serif;
      font-size: 0.9em;
      min-width: 400px;
      border-radius: 5px 5px 0 0;
      overflow: hidden;
      box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
      }
    .content-table th,
    .content-table td{
      padding: 12px 15px;
    }
    .content-table tbody tr{
      border-bottom: 1px solid #2466ea;
    }
    .content-table tbody tr:last-of-type{
      border-bottom: 2px solid #2466ea;
    }
    .button {
        padding: 2px 30px;
        border: none;
        background-color: #2466ea;
        font-family: sans-serif;
        font-weight: bold;
        font-size: 16px;
        color: #fff;
        border-radius: 50px;
        cursor: pointer;
        margin: auto;
        text-align: center;
    }
    button{
      margin: auto;
    }
</style>

<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Haii!!, {{nama}}</a>
    <button type="button"><a href="{% url 'wishlist:logout' %}" class="button">Logout</a></button>
    </div>
    </nav>

<h5 class="text">Nama:</h5>
<p class="text1">{{nama}}</p>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>
<body>
<table class="content-table">
    <tr class="tabelcolor">
    <th>Nama Barang</th>
    <th>Harga Barang</th>
    <th>Deskripsi</th>
    </tr>
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %} 
    <tbody id="table">
      
    </tbody>
</table>
<h5 class="text1">Sesi terakhir login: {{ last_login }}</h5>
<form method="POST" action="">
    {% csrf_token %}
    <table>
      <tr>
        <td>Nama Barang: </td>
        <td><input type="text" id="nama_barang" name="nama_barang" placeholder="Nama Barang" class="form-control"></td>
      </tr>

      <tr>
        <td>Harga Barang: </td>
        <td><input type="number" id="harga_barang" name="harga_barang" placeholder="Harga Barang" class="form-control"></td>
      </tr>

      <tr>
        <td>Deskripsi: </td>
        <td><textarea class="form-control" id="deskripsi" name="deskripsi"></textarea></td>
      </tr>

      <tr>
        <td></td>
        <td><input class="btn btn-primary" type="submit" value="Submit" id="addWishlistBtn"></td>
      </tr>
    </table>
  </form>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
  function postNew(e) {
    e.preventDefault()
    const namaBarang = $("#nama_barang").val()
    const hargaBarang = $("#harga_barang").val()
    const deskripsi = $("#deskripsi").val()

    const data = {
      nama_barang: namaBarang,
      harga_barang: hargaBarang,
      deskripsi,
      csrfmiddlewaretoken: "{{ csrf_token }}"
    }

    $.ajax({
      type: 'POST',
      url: '{% url "wishlist:create_wishlist" %}',
      data: data, 
      success: () => {
        alert("Done!")
        fetchData()
      },
      dataType: 'json'
    });
  }

  function writeTable(data) {
    const table = $("#table")
    table.empty()
    for (let i = 0; i < data.length; i++) {
      table.append(`
        <tr>
          <td>${data[i].fields.nama_barang}</td>
          <td>${data[i].fields.harga_barang}</td>
          <td>${data[i].fields.deskripsi}</td>
        </tr>
        `)
    }
  }

  function fetchData() {
    $.get("/wishlist/json", writeTable)
  }

  $(document).ready(() => {
    $("#addWishlistBtn").click(postNew)
    fetchData()
  })
</script>
{% endblock content %}